### ISSUE TITLE
--update and --fudate return 404.

### ISSUE THREAD

**Issue by jpmedley** [epistemex/mdncomp#7]
I think that says it all.

**Comment by epistemex** [comment]
Hi, what version are you at? Have you tried to upgrade to latest version via NPM (changes has been made to the data service which has new support from mdncomp v. 1.22+)?  npm i -g mdncomp

**Comment by epistemex** [comment]
Hi, you're probably running a pre-1.22 version.

The data service URLs has changed (very) recently and has support in newer versions from and including v1.22 (current release is 1.23). I did announce it a few weeks back but the problem should be solved by simply updating the package via NPM and then try --*update again.

The new version, co-incidentally, also addresses data redundancy (secondary data source in case main is unavailable). It now also updates via patches and compressed data.

**Comment by epistemex** [comment]
How did it go @jpmedley? Let me know if you still have the same problem after updating.

**Comment by epistemex** [comment]
Closing this due to no response; assuming it was solved by simply updating to v.1.22+ as the data-repo URLs changed from that version and the old data-repo was removed.

For future visitors I would recommend clicking the "Watch" button to get updates/announcement (currently exactly 0 persons are watching..).
